name: Test
on:
  push: { branches: master }

jobs:
  test:
    name: Matrix test
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['./my-app', './ang-concepts'] }

    steps:
         - name: Setup Node
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm install 
      - name: Do something with the matrix value
        working-directory: ${{ matrix.dir }}