name: Cypress tests
on:
  pull_request:
# jobs:
#   my_first_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v3
#       - name: Use local my-action
#         uses: ./.github/workflows/e2e




jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest

    # env:
    #   working-directory: ./test-webdriverIO/my-app
    steps:
      - name: config

        # working-directory: my-app
        run: |
          ls

      - name: Checkout
        uses: actions/checkout@v3
      - name: 
        run: |
          pwd

  
      - name: config
        working-directory: /home/runner/work/test-webdriverIO/test-webdriverIO/my-app
      - name: cy
        uses: cypress-io/github-action@v5

      # - run: npm start
      #   working-directory: ./test-webdriverIO/my-app


      

#   my_second_job:
#     name: My second job
#     runs-on: ubuntu-latest
#     env: 
#       working-directory: ./ang-concepts
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Set up node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16
#       - name: Run E2E tests
#         uses: cypress-io/github-action@v4.2.0
#         with:
#           start: npm start
#           record: false
#           browser: chrome
#           wait-on: http://localhost:4200/
#           wait-on-timeout: 100000
#           command: npm install