name: Cypress tests
on:
  pull_request:
# jobs:
#   my_first_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v3
#       - name: Use local my-action
#         uses: ./.github/workflows/e2e




# jobs:
#   cypress-run:
#     name: Cypress run
#     runs-on: ubuntu-latest

    # env:
    #   working-directory: ./test-webdriverIO/my-app
    # steps:


    #   - name: Checkout
    #     uses: actions/checkout@v3
    #   - name: 
    #     run: |
    #       pwd

  

    #   - name: config

    #     working-directory: /home/runner/work/test-webdriverIO/test-webdriverIO/my-app
    #     run: |
    #       pwd
    #   - name: install
    #     run: npm install
    #     working-directory: /home/runner/work/test-webdriverIO/test-webdriverIO/my-app



      # - run: npm start
      #   working-directory: ./test-webdriverIO/my-app


      

  my_second_job:
    name: My second job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run E2E tests
        uses: cypress-io/github-action@v5.0.8
        with:
          start: npm install
          command: npm run e2e
          working-directory: /home/runner/work/test-webdriverIO/test-webdriverIO/my-app