name: E2E Test with Cypress on Chrome
on:
  pull_request:

jobs:
  cypress-e2e-Test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Run E2E tests
        uses: cypress-io/github-action@v4.2.0
        with:
          start: npm start
          record: false
          browser: chrome
          wait-on: http://localhost:4200/
          wait-on-timeout: 100000
          command: npm run test